// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CNC_HMI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// --- Funciones de Control ---
void JogXPlus(lv_event_t * e);
void JogXMinus(lv_event_t * e);
void JogYPlus(lv_event_t * e);
void JogYMinus(lv_event_t * e);
void JogZPlus(lv_event_t * e);
void JogZMinus(lv_event_t * e);
void CmdHome(lv_event_t * e);
void CmdStop(lv_event_t * e);
void EmergenciaTotal(lv_event_t * e);
void SelectorMaquina(lv_event_t * e);

// --- Funciones de Archivos y Navegación ---
void IrSeleccionarTarea(lv_event_t * e);
void RefrescarListaArchivos(lv_event_t * e);
void EnviarArchivoDesdeRoller(lv_event_t * e);
void retrocederMain(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
